pushd /Users/raymondleclair/Projects/Addgene/addgene-bioinformatics/local-tmp/bin
rm ace2sam
rm blast2sam.pl
rm bowtie2sam.pl
rm export2sam.pl
rm interpolate_sam.pl
rm maq2sam-long
rm maq2sam-short
rm md5fa
rm md5sum-lite
rm novo2sam.pl
rm plot-bamstats
rm psl2sam.pl
rm sam2vcf.pl
rm samtools
rm samtools.pl
rm seq_cache_populate.pl
rm soap2sam.pl
rm varfilter.py
rm wgsim
rm wgsim_eval.pl
rm zoom2sam.pl
popd

pushd /Users/raymondleclair/Projects/Addgene/addgene-bioinformatics/local-tmp/share/man/man1
rm samtools-addreplacerg.1
rm samtools-bedcov.1
rm samtools-calmd.1
rm samtools-cat.1
rm samtools-collate.1
rm samtools-depad.1
rm samtools-depth.1
rm samtools-dict.1
rm samtools-faidx.1
rm samtools-fasta.1
rm samtools-fastq.1
rm samtools-fixmate.1
rm samtools-flags.1
rm samtools-flagstat.1
rm samtools-fqidx.1
rm samtools-idxstats.1
rm samtools-index.1
rm samtools-markdup.1
rm samtools-merge.1
rm samtools-mpileup.1
rm samtools-phase.1
rm samtools-quickcheck.1
rm samtools-reheader.1
rm samtools-rmdup.1
rm samtools-sort.1
rm samtools-split.1
rm samtools-stats.1
rm samtools-targetcut.1
rm samtools-tview.1
rm samtools-view.1
rm samtools.1
rm wgsim.1
popd
